print("-------------Tuplas-------------\n")

numers = (1, 2, 3, 5)
print(numers)
print(type(numers))
print()
string = ('nico', 'zule', 'santi', 'juan', 'nico')
print(string)
print(type(string))
print()
print(string)
print(string.index('zule'))
print(string.count('nico'))
print()
my_list = list(string)
print(my_list)
my_list_1 = tuple(my_list)
print(my_list_1)