print("*" * 31)
print("*            USUARIO          *")
print("*" * 31)
print("*      *   *  ***  *   *   ** *")
print("*     *   *   *   *   *  *  * *")
print("*    *   *   *   * * *   *    *")
print("*   * * *   *   *  **    *    *")
print("*  * * *   *   *   *  *  *    *")
print("*  * *   ***  *   *   **      *")
print("*" * 31)

print("*" * 31)
print("*         COMPUTADORA         *")
print("*" * 31)
print("*      *   *  ***  *   *   ** *")
print("*     *   *   *   *   *  *  * *")
print("*    *   *   *   * * *   *    *")
print("*   * * *   *   *  **    *    *")
print("*  * * *   *   *   *  *  *    *")
print("*  * *   ***  *   *   **      *")
print("*" * 31)